version: "3"

services:
  chan:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./chan:/chan
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=chan_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass123
