# Generated by Django 3.1.3 on 2020-11-08 11:56

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='defaults/default.jpg', null=True, upload_to=core.models.avatar_file_path),
        ),
    ]
