# Generated by Django 3.1.3 on 2020-11-08 12:07

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201108_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='defaults/default.png', upload_to=core.models.avatar_file_path),
        ),
    ]
