# Generated by Django 3.1.3 on 2020-11-10 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_board'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Board',
        ),
    ]
